### PR TITLE
A Messages file for the Turkish Translation.

### PR DESCRIPTION
**Pull request by MMDF**
I would like to contribute to make a Turkish translation of this add-on. I will be copying the EN messages.json file into this file.

### CODE REVIEW

**Comment by derjanb** [comment]
Thank you very much.

**Comment by MMDF** [comment]
So, I have forked the project and started working on the translation. I have translated the first 100 lines and I'll be continuing. Here is the fork: https://github.com/MMDF/tampermonkey-i18n I'll create another pull request after I'm done with it.

**Comment by Tmp341** [comment]
I had started translating, but after some point i got busy and dropped. I'm gonna send you the lines i've done, you can check and continue from that point.

**Comment by Tmp341** [comment]
Here it is. This one is an old one, so just use copy paste. Don't merge with yourself. Because it seems there are a lot of changes since last i checked
[.](https://github.com/Tmp341/tampermonkey-i18n/commit/39306a21a12dd0097f591fb0f095caa2652a3f02)

**Comment by MMDF** [comment]
Ok. So I'll be using that but the thing is I've used "kod" instead of "betik" because "kod" is a more popular word than "betik" so it will be recognized by more people.

**Comment by Tmp341** [comment]
You mean, script's meaning is "kod" instead of "betik"? Anyway, use whichever suits you. Good luck.

**Pull request closed without merging**
