### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
Update Italian language.
Added new strings.
Revised old strings.

### CODE REVIEW

**Comment by derjanb** [comment]
Thank you very much! :)

**Comment by bovirus** [comment]
@derjanb 

Thanks to merge the language.
Where can I get latest build (beta) with this new language?
Where can I get the source structure to make the new build myself?

**Comment by derjanb** [comment]
@bovirus You can get it from here: https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

**Comment by bovirus** [comment]
@derjanb 

I found an error in language file.
I will post the changes and I hope to it as soon as.

Please take care that appear a window untranslated. 
I attached the screenshot.

Also all key mapping name are untranslated.
Please include all keys mapping in language file.

tampermonkey-ui-02

tampermonkey-ui-01

**Pull request merged**
